categories:
  KuHteammanagement:
    label: 'KIND&HUND Teammanagement'
  KuHteammanagement.team:
    label: 'Team'
    parent: KuHteammanagement

settings:
  KuHteammanagement.newTeamGroupID:
    label: 'Gruppen-ID'
    category: KuHteammanagement.team
    description: 'ID der Gruppe "neues Team"'
    type: string
    default: '1'
