categories:
  KuHteammanagement:
    label: 'KIND&HUND Distribution'
  KuHteammanagement.templates:
    label: 'Templates'
    parent: KuHteammanagement
  KuHteammanagement.pages:
    label: 'Pages'
    parent: KuHteammanagement
  KuHteammanagement.layout:
    label: 'Layout'
    parent: KuHteammanagement
  KuHteammanagement.settings:
    label: 'Settings'
    parent: KuHteammanagement

settings:
  KuHteammanagement.templateRootPath:
    label: 'Templates'
    category: KuHteammanagement.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Templates/'
  KuHteammanagement.partialRootPath:
    label: 'Partials'
    category: KuHteammanagement.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Partials/'
  KuHteammanagement.layoutRootPath:
    label: 'Layouts'
    category: KuHteammanagement.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Layouts/'
  KuHteammanagement.loginPid:
    label: 'Default FE-User Login PID'
    category: KuHteammanagement.pages
    description: 'Page containing fe_login Form'
    type: int
    default: 0
  KuHteammanagement.editorUsergroupUid:
    label: 'Frontend admin user group UID'
    category: KuHteammanagement.settings
    description: 'Enter the uid of the front end user group that should be allowed to edit blogs and post in the frontend in the admin plugin. '
    type: int
    default: 0
  KuHteammanagement.postsPerPage:
    label: 'Posts per page'
    category: KuHteammanagement.settings
    description: 'How many posts should be displayed per page of pagination?'
    type: int
    default: 3
  KuHteammanagement.defaultGravator:
    label: 'Default gravator icon'
    category: KuHteammanagement.layout
    description: 'This icon is displayed for a comment if the email address of the commentary is not registered. '
    type: string
    default: 'EXT:blog_example/Resources/Public/Icons/default_gravatar.gif'
