services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Conpassione\Kuhdist\:
    resource: '../Classes/*'

  Conpassione\Kuhdist\EventListener\TcaToRteConfiguration:
    tags:
      - name: 'event.listener'
        event: 'TYPO3\CMS\RteCKEditor\Form\Element\Event\AfterPrepareConfigurationForEditorEvent'
