name: conpassione/newteamenroll
typeField: type
typeName: kuhnewteamenroll
title: 'Neues Team'
table: tx_conpassione_newteamenroll
prefixFields: false
languageAware: false
labelField:
  - lastname
  - firstname
  - dog
  - mobile
  - email
security:
  ignorePageTypeRestriction: true

fields:
  - identifier: lastname
    type: Text
    label: 'Name'
    required: true
  - identifier: firstname
    type: Text
    label: 'Vorname'
  - identifier: mobile
    type: Text
    label: 'Mobile'
  - identifier: email
    type: Text
    label: 'E-Mail'
    required: true
  - identifier: message
    type: Textarea
    label: 'Message'
    rows: 6
    enableRichtext: true
  - identifier: dog
    type: Text
    label: 'Dog'
  - identifier: breed
    type: Text
    label: 'Breed'
  - identifier: birthdate
    type: DateTime
    label: 'Birthdate'
    format: date
